### ISSUE TITLE
release fails to build in ubuntu 18.04.1 in WSL

### ISSUE THREAD

**Issue by kyhwana** [int08h/roughenough#7]
Trying to build via "cargo build --release" on the master branch (downloaded via fails with the following errors:
 Compiling ctrlc v3.1.1
error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/kyhwana/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.13.2/build.rs:375:9
    |
375 |     let (_, _, perlasm_format) = ASM_TARGETS.iter().find(|entry| {
    |         ^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&(_, _, perlasm_format)`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/kyhwana/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.13.2/build.rs:674:9
    |
674 |     for (src, dst) in src_dst {
    |         ^^^^^^^^^^ help: consider using a reference: `&(src, dst)`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/kyhwana/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.13.2/build.rs:737:35
    |
737 |             RING_SRCS.iter().any(|(_, f)| cmp(f)) ||
    |                                   ^^^^^^ help: consider using a reference: `&(_, f)`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> /home/kyhwana/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.13.2/build.rs:741:35
    |
741 |             RING_SRCS.iter().any(|(_, f)| cmp(f)) ||
    |                                   ^^^^^^ help: consider using a reference: `&(_, f)`

error: aborting due to 4 previous errors

error: Could not compile `ring`.
warning: build failed, waiting for other jobs to finish...
error: build failed

cargo --version
cargo 0.26.0
rustc --version
rustc 1.25.0

**Comment by int08h** [comment]
Hello @kyhwana, Roughenough uses [ring](https://github.com/briansmith/ring) v0.13.x for cryptographic operations. According to [ring's documentation](https://github.com/briansmith/ring#versioning--stability) it guarantees compatibility only with the latest Stable Rust (which is currently **1.29**).

The version Ubuntu 18.04.1 provides (given the output of `rustc --version` you reported) is **1.25** which seems to be too old to compile Ring. 

I'll update the docs to reflect this requirement.
